name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW Cross-Compiler
      run: |
        sudo apt update
        sudo apt install -y mingw-w64

    - name: Build main.exe
      run: |
        # Use MinGW for native Windows executable
        x86_64-w64-mingw32-gcc -I . main.c Zydis.c -o cachekey-extract.exe -lpsapi -lshell32 -lntdll -static-libgcc

    - name: Upload release artifact
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./cachekey-extract.exe
        asset_name: cachekey-extract.exe
        asset_content_type: application/octet-stream

    - name: Upload build artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: cachekey-extract
        path: cachekey-extract.exe